// <auto-generated />
using System;
using AC.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AC.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528193124_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AC.Domain.Entities.Arbitrator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Exp")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.ToTable("Arbitrators", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArbitratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefendantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PlaintiffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArbitratorId");

                    b.HasIndex("DefendantId");

                    b.HasIndex("PlaintiffId");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefendantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaintiffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.HasIndex("DefendantId");

                    b.HasIndex("PlaintiffId");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.CourtRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CourtRules", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Defendant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.ToTable("Defendants", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Plaintiff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.ToTable("Plaintiffs", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.SettlementProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefendantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("DefendantId");

                    b.ToTable("SettlementProposals", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Verdict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArbitratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArbitratorId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("Verdicts", (string)null);
                });

            modelBuilder.Entity("CaseCourtRules", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourtRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("CaseId", "CourtRuleId");

                    b.HasIndex("CourtRuleId");

                    b.ToTable("CaseCourtRules", (string)null);
                });

            modelBuilder.Entity("AC.Domain.Entities.Case", b =>
                {
                    b.HasOne("AC.Domain.Entities.Arbitrator", "Arbitrator")
                        .WithMany()
                        .HasForeignKey("ArbitratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AC.Domain.Entities.Defendant", "Defendant")
                        .WithMany()
                        .HasForeignKey("DefendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AC.Domain.Entities.Plaintiff", "Plaintiff")
                        .WithMany()
                        .HasForeignKey("PlaintiffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arbitrator");

                    b.Navigation("Defendant");

                    b.Navigation("Plaintiff");
                });

            modelBuilder.Entity("AC.Domain.Entities.Claim", b =>
                {
                    b.HasOne("AC.Domain.Entities.Case", null)
                        .WithOne("Claim")
                        .HasForeignKey("AC.Domain.Entities.Claim", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AC.Domain.Entities.Defendant", "Defendant")
                        .WithMany()
                        .HasForeignKey("DefendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AC.Domain.Entities.Plaintiff", "Plaintiff")
                        .WithMany()
                        .HasForeignKey("PlaintiffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Defendant");

                    b.Navigation("Plaintiff");
                });

            modelBuilder.Entity("AC.Domain.Entities.Comment", b =>
                {
                    b.HasOne("AC.Domain.Entities.Case", "CaseAssigned")
                        .WithMany("Comments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseAssigned");
                });

            modelBuilder.Entity("AC.Domain.Entities.SettlementProposal", b =>
                {
                    b.HasOne("AC.Domain.Entities.Case", "CaseAssigned")
                        .WithMany("Proposals")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AC.Domain.Entities.Defendant", "Defendant")
                        .WithMany()
                        .HasForeignKey("DefendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseAssigned");

                    b.Navigation("Defendant");
                });

            modelBuilder.Entity("AC.Domain.Entities.Verdict", b =>
                {
                    b.HasOne("AC.Domain.Entities.Arbitrator", "Arbitrator")
                        .WithMany()
                        .HasForeignKey("ArbitratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AC.Domain.Entities.Case", "CaseAssigned")
                        .WithOne("Verdict")
                        .HasForeignKey("AC.Domain.Entities.Verdict", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arbitrator");

                    b.Navigation("CaseAssigned");
                });

            modelBuilder.Entity("CaseCourtRules", b =>
                {
                    b.HasOne("AC.Domain.Entities.Case", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AC.Domain.Entities.CourtRule", null)
                        .WithMany()
                        .HasForeignKey("CourtRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AC.Domain.Entities.Case", b =>
                {
                    b.Navigation("Claim");

                    b.Navigation("Comments");

                    b.Navigation("Proposals");

                    b.Navigation("Verdict");
                });
#pragma warning restore 612, 618
        }
    }
}
